keys:
  - &nuv6660 age1e02f5up2s4a4frjpyg00hrhcyrhmzzq63ecetvnpal7knerhrghqmh857a
  - &carbonate age1zdd8aepdmpn237z2sly9u0cpvnyp8dc0sjydxy8tfypx9t9szyrq7lg3kl
creation_rules:
  - path_regex: secrets(\\[^\\]+?|/[^/]+?)$
    key_groups:
      - age:
          - *nuv6660
          - *carbonate
