keys:
  - &carbonate age13h26qgss0xlm35qktka585q6jf24y2sxc2crh5efmttvgevpv4equsk2hf
  - &misen age1qwjeqgxfaj533jer3pgcpl5wkuvudjzj4x5yw6fgan4akfyquszqv2cr0e
  - &tweeze age1fekzchup0fwk5329smzzshpmkvq8vmra5d3pqg69fpk3vllmzp5shzgw5l
  - &vide age1jjpqqt77yyejf4zhlkqyt53qywksamxeqxymm90v4j7xt69xqyhq8r8h48
creation_rules:
  - path_regex: secrets(\\[^\\]+?|/[^/]+?)$
    key_groups:
      - age:
          - *carbonate
          - *misen
          - *tweeze
          - *vide
